sensor:
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_home_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_home_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'kerstboom', 'plastic_blik_en_drankkartons', 'papier', 'restafval', 'takken', 'oude_kleding'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Kerstboom', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval', 'Takken', 'Oude Kleding'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_home_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_home_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_home_' ~l) }}
          {%- endif %}
          {%- endfor %}